"""Single source of truth for the tagline teaser timing + sound design.

Writes:
  timeline.js                    -> window.TEASER (event frames, shared by both formats)
  assets/audio/sfx_*.wav         -> synthesized one-shots (ffmpeg lavfi + sox reverb)
  assets/audio/tagline_sfx.wav   -> final mix, every hit placed sample-exact

Every visual event lives on a 60fps frame. Audio is 48 kHz, so frame f starts at
sample f * 800 exactly - each click/tick/impact lands on the frame its visual
appears. Both the horizontal and vertical renders read the same timeline.js and
play the same WAV, so speed and audio are identical between formats.
"""
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
AUDIO = ROOT / "shared" / "assets" / "audio"
AUDIO.mkdir(parents=True, exist_ok=True)

FPS = 60
SR = 48000
SPF = SR // FPS  # samples per frame (800)

# ---------------------------------------------------------------- copy
LINE1 = "A user-driven ecosystem"
LINE2 = "for real-world businesses"
LINE3 = "that pay you back"
# Horizontal: LINE1 + " " + LINE2 + "..." + " " + LINE3 on one line.
# Vertical:   the two " " events become line breaks (same frame, same click).

# ---------------------------------------------------------------- timing (frames @60fps)
BLINK_START = 0
BLINK_STATE = 12          # 0.2s per on/off state, 2 blinks -> 48 frames
TYPE_A_START = 48         # 0.8s
CHAR_GAP = 2              # 33ms per character (~30 chars/s)
LINE_BREAK_PAUSE = 6      # extra beat after "ecosystem" before "for"
DOTS_LEAD = 8             # beat between "businesses" and first dot
DOT_GAP = 8               # 0.133s between dots
DOTS_HOLD = 12            # hold with all three dots before they vanish
DOTS_GAP_AFTER_CLEAR = 8  # empty beat before the next loop
DOT_LOOPS = 2             # loop 1 clears, the final loop settles as "..."
TYPE_B_LEAD = 12          # beat after dots settle before "that pay you back"
CURSOR_HIDE_AFTER = 12    # cursor disappears 0.2s into the hold
HOLD = 28                 # completed text on screen after last char
BLACK_HOLD = 18           # 0.3s black before the logo slams in
LOGO_TAIL = 180           # 3s logo + impact decay

events = {}
f = TYPE_A_START
type_a = []
for i, ch in enumerate(LINE1 + " " + LINE2):
    type_a.append(f)
    f += CHAR_GAP + (LINE_BREAK_PAUSE if i == len(LINE1) - 1 else 0)
last_a = type_a[-1]

dots = []  # list of loops: {"on": [f1, f2, f3], "off": frame or None}
f = last_a + DOTS_LEAD
for loop in range(DOT_LOOPS):
    on = [f, f + DOT_GAP, f + 2 * DOT_GAP]
    final = loop == DOT_LOOPS - 1
    off = None if final else on[-1] + DOTS_HOLD
    dots.append({"on": on, "off": off})
    f = on[-1] if final else off + DOTS_GAP_AFTER_CLEAR
dots_settled = dots[-1]["on"][-1]

f = dots_settled + TYPE_B_LEAD
type_b = [f + i * CHAR_GAP for i in range(len(" " + LINE3))]
last_b = type_b[-1]

cursor_hide = last_b + CURSOR_HIDE_AFTER
cut = last_b + HOLD
logo = cut + BLACK_HOLD
end = logo + LOGO_TAIL

timeline = {
    "fps": FPS,
    "lines": [LINE1, LINE2, LINE3],
    "blink": {"start": BLINK_START, "state": BLINK_STATE, "count": 2},
    "typeA": type_a,           # len(LINE1) + 1 + len(LINE2) events
    "splitA": len(LINE1),      # index of the " " / line-break event in typeA
    "dots": dots,
    "typeB": type_b,           # index 0 is the " " / line-break event
    "cursorHide": cursor_hide,
    "cut": cut,
    "logo": logo,
    "end": end,
    "durationSec": round(end / FPS, 6),
}
(ROOT / "shared" / "timeline.js").write_text(
    "// Generated by scripts/build_timeline_audio.py - do not edit by hand.\n"
    "window.TEASER = " + json.dumps(timeline, indent=2) + ";\n"
)

# ---------------------------------------------------------------- synthesis helpers
def run(cmd):
    subprocess.run(cmd, check=True)

def lavfi(out, graph, inputs):
    cmd = ["ffmpeg", "-y", "-loglevel", "error"]
    for src in inputs:
        cmd += ["-f", "lavfi", "-i", src]
    cmd += ["-filter_complex", graph, "-map", "[o]", "-ac", "1", "-ar", str(SR), "-c:a", "pcm_s24le", str(out)]
    run(cmd)

# KEY-TAP: soft high-passed noise tap + a rounded "tock" body. ~35ms, fast attack.
click = AUDIO / "sfx_click.wav"
lavfi(click,
      "[0]highpass=f=2200,highpass=f=2200,lowpass=f=9000[n];"
      "[1][n]amultiply,volume=0.55[nt];"
      "[nt][2]amix=inputs=2:normalize=0,highpass=f=180[o]",
      ["anoisesrc=d=0.04:c=white:r=48000:seed=11:a=1",
       "aevalsrc='(1-exp(-t*9000))*exp(-t*240)':d=0.04:s=48000",
       "aevalsrc='(1-exp(-t*6000))*exp(-t*300)*(0.30*sin(2*PI*1750*t)+0.22*sin(2*PI*420*t))':d=0.04:s=48000"])

# DOT-TICK: softer, higher, purely tonal glassy tick. ~30ms.
tick = AUDIO / "sfx_tick.wav"
lavfi(tick, "[0]highpass=f=1500[o]",
      ["aevalsrc='(1-exp(-t*8000))*exp(-t*360)*(0.55*sin(2*PI*3300*t)+0.18*sin(2*PI*5200*t))':d=0.03:s=48000"])

# LOGO IMPACT: hard transient + pitch-dropping sub thump + dense low-mid slam,
# then a sox reverb tail. Attack stays at sample 0; tail decays to silence by ~3s.
impact_dry = AUDIO / "_impact_dry.wav"
lavfi(impact_dry,
      "[0]lowpass=f=7000,highpass=f=120[tn];[1][tn]amultiply,volume=1.1[tr];"      # snap
      "[2]lowpass=f=900,highpass=f=60[bn];[3][bn]amultiply,volume=1.6[body];"       # slam
      "[tr][body][4]amix=inputs=3:normalize=0[o]",
      ["anoisesrc=d=3:c=white:r=48000:seed=23:a=1",
       "aevalsrc='(1-exp(-t*20000))*exp(-t*55)':d=3:s=48000",
       "anoisesrc=d=3:c=pink:r=48000:seed=5:a=1",
       "aevalsrc='(1-exp(-t*9000))*exp(-t*18)':d=3:s=48000",
       # sub: 150Hz -> 38Hz drop, soft-saturated for harmonics on small speakers,
       # a fast punch decay plus a longer resonance that rings out.
       "aevalsrc='(1-exp(-t*3000))*tanh(2.0*sin(2*PI*(38*t+(150-38)/20*(1-exp(-20*t)))))"
       "*(0.70*exp(-t*8)+0.30*exp(-t*1.5))':d=3:s=48000"])

impact_verb = AUDIO / "_impact_verb.wav"
# sox reverb: reverberance, HF damping, room scale, stereo depth, pre-delay, wet gain
run(["sox", str(impact_dry), "-c", "2", str(impact_verb),
     "gain", "-8",  # headroom so the reverb never clips
     "reverb", "72", "55", "100", "80", "0", "-4",
     "fade", "t", "0", "3.0", "1.1"])  # smooth final decay to true silence at 3.0s

impact = AUDIO / "sfx_impact.wav"
# Light glue compression on the body only (no lookahead, attack slower than the
# snap so the transient passes untouched), then peak-normalise to -1 dBFS.
run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(impact_verb),
     "-af", "acompressor=threshold=0.35:ratio=2:attack=8:release=150:makeup=1",
     "-ar", str(SR), "-c:a", "pcm_s24le", str(AUDIO / "_impact_comp.wav")])
run(["sox", str(AUDIO / "_impact_comp.wav"), str(impact), "gain", "-n", "-1"])
(AUDIO / "_impact_comp.wav").unlink()
impact_dry.unlink()
impact_verb.unlink()

# ---------------------------------------------------------------- placement
# Relative levels: impact peaks at -1 dBFS, key taps ~-14 dBFS, dot ticks quieter still.
CLICK_GAIN, TICK_GAIN = 0.42, 0.18
hits = [(click, fr, CLICK_GAIN) for fr in type_a + type_b]
hits += [(tick, fr, TICK_GAIN) for loop in dots for fr in loop["on"]]
hits += [(impact, logo, 1.0)]
srcs = [click, tick, impact]

total_samples = end * SPF
parts, labels = [], []
by_src = {s: [h for h in hits if h[0] == s] for s in srcs}
for si, s in enumerate(srcs):
    group = by_src[s]
    parts.append(f"[{si}]aformat=sample_rates={SR}:channel_layouts=stereo,"
                 f"asplit={len(group)}" + "".join(f"[s{si}_{k}]" for k in range(len(group))))
    for k, (_, fr, vol) in enumerate(group):
        lab = f"h{si}_{k}"
        parts.append(f"[s{si}_{k}]adelay=delays={fr * SPF}S:all=1,volume={vol}[{lab}]")
        labels.append(lab)
parts.append("".join(f"[{l}]" for l in labels) +
             f"amix=inputs={len(labels)}:normalize=0:dropout_transition=0,"
             f"apad=whole_len={total_samples},atrim=end_sample={total_samples}[out]")
graph = ";".join(parts)

mix = AUDIO / "tagline_sfx.wav"
cmd = ["ffmpeg", "-y", "-loglevel", "error"]
for s in srcs:
    cmd += ["-i", str(s)]
cmd += ["-filter_complex", graph, "-map", "[out]", "-ar", str(SR), "-c:a", "pcm_s24le", str(mix)]
run(cmd)

print(json.dumps({k: timeline[k] for k in ("cut", "logo", "end", "durationSec")}))
print("typeA", type_a[0], "->", last_a, "| dots", dots, "| typeB", type_b[0], "->", last_b)
