#!/usr/bin/env node
// npm run weekly — the one command for publishing a new week.
//
//   1. reads data/week.json
//   2. writes data/week.js (window.WEEK_DATA + the resolved beat schedule)
//   3. verifies the scene clips in index.html match the schedule
//   4. renders 1920x1080 to output/talex_weekly_week{N}_16x9.mp4
//
// Flags:  --prepare-only            (steps 1-3 only; used by check/dev)
//         --format 16x9|1x1|9x16|all (default 16x9)
//         --quality draft|looks|delivery
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { readFileSync, writeFileSync, existsSync, mkdirSync, unlinkSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { buildSchedule, DURATION } from "../src/schedule.mjs";
import { FORMATS, BASE, materialize, cleanup } from "./formats.mjs";

const HYPERFRAMES = "hyperframes@0.8.58";
const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const opt = (name, def) => {
  const i = args.indexOf(name);
  return i > -1 && args[i + 1] ? args[i + 1] : def;
};

export function loadData() {
  const data = JSON.parse(readFileSync(join(root, "data", "week.json"), "utf8"));
  const required = ["week", "date", "buyback_usd", "x_injected", "bnb_injected", "price_usd", "revenue_pct", "tx_hash", "cumulative_usd", "holders"];
  for (const k of required) if (!(k in data)) throw new Error(`data/week.json is missing "${k}"`);
  if (!Array.isArray(data.holders) || data.holders.length < 2) throw new Error("data/week.json: holders needs >= 2 entries (first = last week's closing value)");
  for (const h of data.holders) if (typeof h.value !== "number" || typeof h.label !== "string") throw new Error("data/week.json: each holders entry needs {label: string, value: number}");
  return data;
}

export function writeWeekJs(data) {
  const schedule = buildSchedule(data);
  if (!schedule.onBeat) {
    console.warn(`! ${data.holders.length} holders entries exceed the ${schedule.steps.length} musical hits available; day-steps are spread evenly instead of landing on beats.`);
  }
  const payload = { ...data, schedule };
  const js = `// GENERATED by scripts/weekly.mjs from data/week.json + audio/beats.json — do not edit by hand.\n` +
    `window.WEEK_DATA = ${JSON.stringify(payload, null, 2)};\n`;
  writeFileSync(join(root, "data", "week.js"), js);
  return schedule;
}

/** The scene host clips and the audio clip in index.html are static; make sure they match the schedule. */
export function verifyIndex(schedule) {
  const html = readFileSync(join(root, "index.html"), "utf8");
  const problems = [];
  const rootDur = html.match(/data-composition-id="main"[^>]*data-duration="([\d.]+)"/);
  if (!rootDur || Math.abs(+rootDur[1] - DURATION) > 1e-6) problems.push(`root data-duration should be ${DURATION}`);
  for (const [id, s] of Object.entries(schedule.scenes)) {
    const m = html.match(new RegExp(`data-composition-id="${id}"[^>]*data-start="([\\d.]+)"[^>]*data-duration="([\\d.]+)"`));
    const dur = Math.round((s.end - s.start) * 1000) / 1000;
    if (!m) problems.push(`scene host "${id}" not found in index.html`);
    else if (Math.abs(+m[1] - s.start) > 1e-6 || Math.abs(+m[2] - dur) > 1e-6) problems.push(`scene host "${id}" should have data-start="${s.start}" data-duration="${dur}" (has ${m[1]} / ${m[2]})`);
  }
  if (!existsSync(join(root, "audio", "music.mp3"))) problems.push("audio/music.mp3 is missing");
  if (problems.length) throw new Error("index.html does not match src/schedule.mjs / audio/beats.json:\n  - " + problems.join("\n  - "));
}

export function prepare() {
  const data = loadData();
  const schedule = writeWeekJs(data);
  verifyIndex(schedule);
  console.log(`data: week ${data.week} (${data.date}), ${data.holders.length} holders entries; day-steps at ${schedule.steps.join("s, ")}s; badge ${schedule.badgeAt}s; logo ${schedule.logoAt}s`);
  return { data, schedule };
}

function render(formatKey, output, quality) {
  mkdirSync(dirname(output), { recursive: true });
  if (existsSync(output)) unlinkSync(output);
  // Each format renders from a temporary copy of the project laid out for it
  // (see scripts/formats.mjs); the repo keeps a single 16:9 source of truth.
  const dir = materialize(root, formatKey);
  try {
    const cmd = ["--yes", HYPERFRAMES, "render", dir, "-o", output, "-q", quality, "--strict"];
    console.log(`\n> [${formatKey}] npx ${cmd.join(" ")}`);
    const r = spawnSync("npx", cmd, { cwd: root, stdio: "inherit", shell: process.platform === "win32" });
    if (r.status !== 0) throw new Error(`render failed for ${formatKey}`);
    if (!existsSync(output)) throw new Error(`render produced no file at ${output}`);
  } finally {
    cleanup(dir);
  }
  console.log(`wrote ${output}`);
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const { data } = prepare();
  if (!flag("--prepare-only")) {
    const quality = opt("--quality", "looks");
    const want = opt("--format", BASE);
    const keys = want === "all" ? Object.keys(FORMATS) : [want];
    for (const key of keys) {
      if (!FORMATS[key]) throw new Error(`unknown format ${key}`);
      render(key, join(root, "output", `talex_weekly_week${data.week}_${key}.mp4`), quality);
    }
    console.log("\nDone. Outputs in weekly/output/");
  }
}
