#!/usr/bin/env node
// npm run weekly — the one command for publishing a new week.
//
//   1. reads data/week.json
//   2. writes data/week.js (window.WEEK_DATA + computed schedule) for the composition
//   3. rebuilds the music bed (audio/_build/music.mp3) to match the timeline,
//      or processes audio/weekly_music_override.mp3 if it exists
//   4. renders 1:1 and 9:16 to output/talex_weekly_week{N}_1x1.mp4 / _9x16.mp4
//
// Flags:  --prepare-only   (steps 1-3 only; used by check/dev)
//         --format 1x1|9x16 (render just one format)
//         --quality draft|looks|delivery
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { readFileSync, writeFileSync, existsSync, mkdirSync, unlinkSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { buildSchedule, SLAM_AT, STAMP_AT, DURATION } from "../src/schedule.mjs";
import { generateBeat } from "../audio/generate_beat.mjs";
import { ffmpeg } from "../audio/synth.mjs";
import { materialize, cleanup } from "./formats.mjs";

const HYPERFRAMES = "hyperframes@0.8.58";
const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const opt = (name, def) => {
  const i = args.indexOf(name);
  return i > -1 && args[i + 1] ? args[i + 1] : def;
};

const OVERRIDE = join(root, "audio", "weekly_music_override.mp3");
const MUSIC_OUT = join(root, "audio", "_build", "music.mp3");

export function loadData() {
  const data = JSON.parse(readFileSync(join(root, "data", "week.json"), "utf8"));
  const required = ["week", "date", "buyback_usd", "x_injected", "bnb_injected", "price_usd", "revenue_pct", "tx_hash", "cumulative_usd", "holders"];
  for (const k of required) if (!(k in data)) throw new Error(`data/week.json is missing "${k}"`);
  if (!Array.isArray(data.holders) || data.holders.length < 2) throw new Error("data/week.json: holders needs >= 2 entries (first = last week's closing value)");
  for (const h of data.holders) if (typeof h.value !== "number" || typeof h.label !== "string") throw new Error("data/week.json: each holders entry needs {label: string, value: number}");
  return data;
}

export function writeWeekJs(data) {
  const schedule = buildSchedule(data);
  if (schedule.stepsOverflow) {
    console.warn(`! ${data.holders.length} holders entries do not fit the chart window; the last steps land after ${schedule.lastStepAt}s. Consider fewer entries.`);
  }
  const payload = { ...data, schedule };
  const js = `// GENERATED by scripts/weekly.mjs from data/week.json — do not edit by hand.\n` +
    `window.WEEK_DATA = ${JSON.stringify(payload, null, 2)};\n`;
  writeFileSync(join(root, "data", "week.js"), js);
  return schedule;
}

export function prepareMusic(data, schedule) {
  mkdirSync(dirname(MUSIC_OUT), { recursive: true });
  if (existsSync(OVERRIDE)) {
    console.log(`music: using override ${OVERRIDE}`);
    // Trim/pad to the video length, level it, duck under the two hit sounds,
    // fade in at the start and out at the end — same envelope as the generated bed.
    const duck = `1-0.55*exp(-pow((t-${SLAM_AT})/0.22,2))*gte(t,${SLAM_AT - 0.04})-0.4*exp(-pow((t-${STAMP_AT})/0.2,2))*gte(t,${STAMP_AT - 0.04})`;
    const af = [
      `atrim=0:${DURATION}`,
      `apad=whole_dur=${DURATION}`,
      `loudnorm=I=-15:TP=-1.5:LRA=11`,
      `volume='${duck}':eval=frame`,
      `afade=t=in:st=0:d=0.6`,
      `afade=t=out:st=${schedule.fadeOutStart}:d=${(DURATION - schedule.fadeOutStart).toFixed(2)}`,
    ].join(",");
    ffmpeg(["-i", OVERRIDE, "-af", af, "-ar", "44100", "-codec:a", "libmp3lame", "-b:a", "192k", MUSIC_OUT]);
    return { source: "override", out: MUSIC_OUT };
  }
  const r = generateBeat(data, MUSIC_OUT);
  console.log(`music: generated ${r.schedule.bpm} BPM beat; accents at ${[r.schedule.slamAt, r.schedule.stampAt, ...r.schedule.steps, r.schedule.badgeAt, r.schedule.logoAt].join("s, ")}s`);
  return { source: "generated", out: MUSIC_OUT };
}

export function prepare() {
  const data = loadData();
  const schedule = writeWeekJs(data);
  prepareMusic(data, schedule);
  console.log(`data: week ${data.week} (${data.date}), ${data.holders.length} holders entries, step every ${schedule.stepInterval}s`);
  return { data, schedule };
}

function render(formatKey, output, quality) {
  mkdirSync(dirname(output), { recursive: true });
  if (existsSync(output)) unlinkSync(output);
  // Each format renders from a temporary copy of the project laid out for it
  // (see scripts/formats.mjs); the repo keeps a single 1:1 source of truth.
  const dir = materialize(root, formatKey);
  try {
    const cmd = ["--yes", HYPERFRAMES, "render", dir, "-o", output, "-q", quality, "--strict"];
    console.log(`\n> [${formatKey}] npx ${cmd.join(" ")}`);
    const r = spawnSync("npx", cmd, { cwd: root, stdio: "inherit", shell: process.platform === "win32" });
    if (r.status !== 0) throw new Error(`render failed for ${formatKey}`);
    if (!existsSync(output)) throw new Error(`render produced no file at ${output}`);
  } finally {
    cleanup(dir);
  }
  console.log(`wrote ${output}`);
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const { data } = prepare();
  if (!flag("--prepare-only")) {
    const quality = opt("--quality", "looks");
    const only = opt("--format", null);
    const N = data.week;
    const outDir = join(root, "output");
    if (!only || only === "1x1") render("1x1", join(outDir, `talex_weekly_week${N}_1x1.mp4`), quality);
    if (!only || only === "9x16") render("9x16", join(outDir, `talex_weekly_week${N}_9x16.mp4`), quality);
    console.log("\nDone. Outputs in weekly/output/");
  }
}
