// Generated by scripts/build_timeline_audio.py - do not edit by hand.
window.TEASER = {
  "fps": 60,
  "lines": [
    "A user-driven ecosystem",
    "for real-world businesses",
    "that pay you back"
  ],
  "blink": {
    "start": 0,
    "state": 12,
    "count": 2
  },
  "typeA": [
    48,
    50,
    52,
    54,
    56,
    58,
    60,
    62,
    64,
    66,
    68,
    70,
    72,
    74,
    76,
    78,
    80,
    82,
    84,
    86,
    88,
    90,
    92,
    100,
    102,
    104,
    106,
    108,
    110,
    112,
    114,
    116,
    118,
    120,
    122,
    124,
    126,
    128,
    130,
    132,
    134,
    136,
    138,
    140,
    142,
    144,
    146,
    148,
    150
  ],
  "splitA": 23,
  "dots": [
    {
      "on": [
        158,
        166,
        174
      ],
      "off": 186
    },
    {
      "on": [
        194,
        202,
        210
      ],
      "off": null
    }
  ],
  "typeB": [
    222,
    224,
    226,
    228,
    230,
    232,
    234,
    236,
    238,
    240,
    242,
    244,
    246,
    248,
    250,
    252,
    254,
    256
  ],
  "cursorHide": 268,
  "cut": 284,
  "logo": 302,
  "end": 482,
  "durationSec": 8.033333
};
